version: "3.9"

services:
  api:
    container_name: api
    build: .
    healthcheck:
      test: curl -fsS localhost:3000/v1/healthcheck
    environment:
      - LOAD_ENV_FILE=true
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/.env
