version: "3.9"

services:
  api:
    container_name: api
    build: .
    healthcheck:
      test: curl -fsS localhost:${PORT}/v1/healthcheck
    environment:
      - LOAD_ENV_FILE=true
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./.env:/.env
