version: "3.9"

services:
  api:
    image: docker.io/gustavocs789/read-manager-main-api-signed:latest
    healthcheck:
      test: curl -fsS localhost:${PORT}/v1/healthcheck
    environment:
      - LOAD_ENV_FILE=true
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./.env:/.env
