// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "gustavocs789@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/healthcheck": {
            "get": {
                "description": "Check health of API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.CheckResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.CheckResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "system_info": {
                    "$ref": "#/definitions/health.System_info"
                }
            }
        },
        "health.System_info": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://read-manager-main-api.onrender.com",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Read Manager Main API",
	Description:      "This is a API for a reader manager.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
